// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/acceptProjectInterest/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Accepting Freelancer to Project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Freelancer which you want to accept",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProjectAcceptMemberParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/addEducation": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "Add User Education",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Data Format to add education",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EducationParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/addExperience": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Adding User Experience",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Data Format to add experience",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExperienceParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/addPortfolio": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Portfolio"
                ],
                "summary": "Adding User Portfolio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Portfolio Description",
                        "name": "Parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PortfolioRequestParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/addProject": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Adding User Project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Data Format to add project",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/allCountries": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Getting all list of countries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKGetAllCountries"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/allProjectCategory": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Get All Project Category List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKProjectCategory"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/allSkills": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Getting all list of skills",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/change-password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register new user using email and password",
                "parameters": [
                    {
                        "description": "Information needed to change password",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/completeProject/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Review Done For Project Owner",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/deleteEducation/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "Deleting User Education",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Education ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/deleteExperience/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Deleting User Experience",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/deletePortfolio/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Portfolio"
                ],
                "summary": "Deleting User Portfolio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/deleteProject/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Deleting User Project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/editEducation/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Education"
                ],
                "summary": "Updating User Education",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Education ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Education Description",
                        "name": "Description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EducationParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/editExperience/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Experience"
                ],
                "summary": "Updating User Experience",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Experience ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Experience Description",
                        "name": "Description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExperienceParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/editPortfolio/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Portfolio"
                ],
                "summary": "Updating User Portfolio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Portfolio Description",
                        "name": "Description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PortfolioRequestParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/editProject/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Edit User Project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Format to edit project",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EditProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/editSkills": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Updating User Skills",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Skills ID List",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateSkills"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login user using email and password",
                "parameters": [
                    {
                        "description": "Account",
                        "name": "parameter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginUserPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKLogin"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/projectDetail/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "User Project Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKProjectDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register new user using email and password",
                "parameters": [
                    {
                        "description": "Account",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegistrationUserUsingPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/resetPassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Reset Password (Forget Password Feature)",
                "parameters": [
                    {
                        "description": "Information needed to change password",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/searchProject": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Search and filter project here",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "newest",
                            "highestprice",
                            "lowestprice"
                        ],
                        "type": "string",
                        "description": "Sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "description": "Filter Skills",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Category",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SearchProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/submitProjectForReview/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Submit Project for review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/submitProjectInterest/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Submit Project Interest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/updateNewPassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Password (after reset password)",
                "parameters": [
                    {
                        "description": "Information needed to update password",
                        "name": "Info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/updateProfile": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Updating User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Data for User Profile",
                        "name": "Description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/uploadAttachment": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Uploading Attachment here",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Upload File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/uploadPicture": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Uploading Picture here",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Upload File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithStringData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/userProfile": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Profile Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKGetUserProfile"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/userProfile/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Profile Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKGetUserProfile"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/userProjects": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "User Projects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKGetUserProject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        },
        "/userReview": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseOKUserReviews"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Add User Review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Data Format to add review",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseWithNoBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddReview": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "projectID": {
                    "type": "integer"
                },
                "starRating": {
                    "type": "integer"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "models.ChangePassword": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "models.CountryData": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "type": "string"
                },
                "countryName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.CountryDataProfile": {
            "type": "object",
            "properties": {
                "countryName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.CreateProject": {
            "type": "object",
            "properties": {
                "attachment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.EditProject": {
            "type": "object",
            "properties": {
                "attachment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.EducationParameters": {
            "type": "object",
            "properties": {
                "endYear": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                }
            }
        },
        "models.EducationReturnValue": {
            "type": "object",
            "properties": {
                "endYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                }
            }
        },
        "models.ExperienceParameters": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "endYear": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                }
            }
        },
        "models.ExperienceReturnValue": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "endYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                }
            }
        },
        "models.GetUserProjectResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isOwner": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.LoginUserPassword": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.OwnerInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "member": {
                    "type": "string"
                },
                "phoneCode": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "integer"
                },
                "projectCompleted": {
                    "type": "integer"
                }
            }
        },
        "models.PageInfoSchema": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.PortfolioRequestParameter": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "endYear": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.PortfolioReturnParameter": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "endYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "startYear": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.ProjectAcceptMemberParameter": {
            "type": "object",
            "properties": {
                "freelancerID": {
                    "type": "integer"
                },
                "trelloKey": {
                    "type": "string"
                }
            }
        },
        "models.ProjectCategoryData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ProjectDetailInterestedMember": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                }
            }
        },
        "models.ProjectDetailResponse": {
            "type": "object",
            "properties": {
                "attachment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProjectLinksResponse"
                    }
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interestedMembers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProjectDetailInterestedMember"
                    }
                },
                "owner": {
                    "type": "object",
                    "$ref": "#/definitions/models.OwnerInfo"
                },
                "price": {
                    "type": "number"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.ProjectInformationForReview": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.ProjectLinksResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "projectLink": {
                    "type": "string"
                }
            }
        },
        "models.RegistrationUserUsingPassword": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "location": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "phoneCode": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "integer"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ResetPassword": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKGetAllCountries": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CountryData"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKGetUserProfile": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/models.UserProfile"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKGetUserProject": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GetUserProjectResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKLogin": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/models.TokenResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKProjectCategory": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProjectCategoryData"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKProjectDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/models.ProjectDetailResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseOKUserReviews": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ReviewInfo"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseWithNoBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ResponseWithStringData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ReviewInfo": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "project": {
                    "type": "object",
                    "$ref": "#/definitions/models.ProjectInformationForReview"
                },
                "reviewer": {
                    "type": "object",
                    "$ref": "#/definitions/models.UserInformationForReview"
                },
                "starRating": {
                    "type": "integer"
                }
            }
        },
        "models.SearchProjectQuery": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "skill": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.SearchProjectResponse": {
            "type": "object",
            "properties": {
                "PageMeta": {
                    "type": "object",
                    "$ref": "#/definitions/models.PageInfoSchema"
                },
                "project": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SearchProjectQuery"
                    }
                }
            }
        },
        "models.TokenResponse": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.UpdateProfile": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "location": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UpdateResetPassword": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.UpdateSkills": {
            "type": "object",
            "properties": {
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.UserInformationForReview": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                }
            }
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EducationReturnValue"
                    }
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExperienceReturnValue"
                    }
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "location": {
                    "type": "object",
                    "$ref": "#/definitions/models.CountryDataProfile"
                },
                "member": {
                    "type": "string"
                },
                "phoneCode": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "integer"
                },
                "picture": {
                    "type": "string"
                },
                "portfolio": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PortfolioReturnParameter"
                    }
                },
                "projectCompleted": {
                    "type": "integer"
                },
                "skill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserSkills"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserSkills": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "Swagger API",
	Description: "Swagger API for Golang Project PMS + Freelancer.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
